_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
alpha:
    value: 0.005
batch_size:
    value: 256
beta:
    value: 3
deterministic_policy:
    value: false
discount:
    value: 0.99
env_name:
    value: tclab-mpc-iql
eval_period:
    value: 5000
exp_name:
    value: tau_0.9_300000
hidden_dim:
    value: 256
learning_rate:
    value: 0.0003
log_dir:
    value: ./runs
max_episode_steps:
    value: 1200
method:
    value: simulator
n_eval_episodes:
    value: 10
n_hidden:
    value: 2
n_steps:
    value: 300000
npz_path:
    value: C:\Users\Developer\TCLab\Data\MPC\mpc_reward.npz
sample_interval:
    value: 5
seed:
    value: 0
tau:
    value: 0.9
